<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="G09INXNP33297X1" failures="6" tests="10" name="Surefire test" time="17.539" errors="0" timestamp="2024-02-29T19:53:30 IST">
  <testcase classname="api.test.DDTests" name="testPostUser" time="0.024">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:678)
at java.base/java.lang.Integer.parseInt(Integer.java:786)
at api.test.DDTests.testPostUser(DDTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testPostUser -->
  <testcase classname="api.test.DDTests" name="testPostUser" time="0.001">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:678)
at java.base/java.lang.Integer.parseInt(Integer.java:786)
at api.test.DDTests.testPostUser(DDTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testPostUser -->
  <testcase classname="api.test.DDTests" name="testPostUser" time="0.001">
    <failure type="java.lang.NumberFormatException" message="Cannot parse null string">
      <![CDATA[java.lang.NumberFormatException: Cannot parse null string
at java.base/java.lang.Integer.parseInt(Integer.java:630)
at java.base/java.lang.Integer.parseInt(Integer.java:786)
at api.test.DDTests.testPostUser(DDTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testPostUser -->
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="3.693"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.479"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.38"/>
  <testcase classname="api.test.UserTests" name="testPostUser" time="2.024"/>
  <testcase classname="api.test.UserTests" name="testGetUser" time="1.344">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testGetUser(UserTests.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testGetUser -->
  <testcase classname="api.test.UserTests" name="testUpdateUser" time="2.747">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testUpdateUser(UserTests.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUser -->
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.532">
    <failure type="java.lang.AssertionError" message="expected [204] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [204] but found [404]
at api.test.UserTests.testDeleteUserByName(UserTests.java:89)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- Surefire test -->
